  
name: "Path lister action"
description: "Lists path of all the files of specified type in the specificied folder/directory"
author: "Rishabh Raizada"
inputs:
  path:
    description: "Path to find the files"
    required: true
outputs:
  path_count:
    description: "Number of files found with the extension"
  paths:
    description: "Path of all the files with the extension"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "list"
  color: "red"
