# This is a basic workflow that is manually triggered

name: Generate Filelist CSV
on: [push]

jobs:
  hmmm-watdo:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"

    - name: Check out repository code
      uses: actions/checkout@v2

    - run: echo "${{ github.repository }} repository has been cloned"

    - name: List files in repo
      working-directory: ${{ github.workspace }}
      run: git ls-files > ./a.csv

    - name: git add
      run: git add -N -f ./a.csv

    - run: echo "${{ job.status }}. Yay"
