# This is a basic workflow that is manually triggered
name: Generate Filelist CSV
on: [push]
jobs:
  hmmm-watdo:
    runs-on: ubuntu-latest
    steps:
    - name: Write to CSV file
      uses: gr2m/write-csv-file-action@v1.x
      with:
        path: data/files.csv
        columns: cname 1, cname 2
#         for i in ${{ steps.pl.outputs.paths }}; do echo $i done
        "cname 1": 11
        "cname 2": 2

    - run: echo "${{ job.status }}. Yay"
