# This is a basic workflow that is manually triggered

name: Generate Filelist CSV
on: [push]

jobs:
  hmmm-watdo:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: echo "${{ github.repository }} repository has been cloned"
    - name: List files in repo
      run: |
        ls ${{ github.workspace }} --full-tree --name-only
    - name: Write to CSV file
      uses: gr2m/write-csv-file-action@v1.0.0
      with:
        # Relative path to .csv file (example: data/stats.csv)
        path: allfiles.csv
        # Comma separated list of column titles. Inputs with the same names must be set
        columns: Filename
        Filename: ls ${{ github.workspace }} --full-tree --name-only
    - run: echo "${{ job.status }}. Yay"
