# This is a basic workflow that is manually triggered
name: Generate Filelist CSV
on: [push]
jobs:
  hmmm-watdo:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: "3.7"

    - name: Check out repository code
      uses: actions/checkout@v2
    - run: echo "${{ github.repository }} repository has been cloned"

    - name: Fetch action
      id: pl
      uses: bmasaur/msft-images@main
      with:
        path: "OC-Innovation/"

    - name: Write to CSV file
      uses: gr2m/write-csv-file-action@v1.0.0
      with:
        path: ./allfiles.csv
        columns: Filename
        "Filename": ${{ steps.pl.outputs.paths }}

    - run: echo "${{ job.status }}. Yay"
