name: Path lister example
on: [push]
jobs:
  list:
    name: Path lister
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"

      - uses: actions/checkout@v1

      - name: Fetch action
        id: pl
        uses: bmasaur/msft-images@main
        with:
          path: "OC-Innovation/"

      - name: create csv file
        run: |
          echo "${{ steps.pl.outputs.path_count }} file(s) found"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i > ./ab.csv
          done

      - name: git add
        run: git add -N -f ./ab.csv
